Feature/helper scenes
mobillium/iOS-Guidelines pull request #10
Opened 2021-02-11 12:59 UTC by tunayyalverr

2021-02-11 13:54 UTC, alihanaktay approved these changes

2021-02-11 13:58 UTC, mrtcelebi approved these changes

2021-02-11 14:03 UTC, aslanmehmetsalih requested changes

2021-02-11 14:03 UTC, aslanmehmetsalih commented on project-folder-structure.md
> +Scenes should be divided into modules and modules should be under the **Scenes** folder. If a scene has flow for more than one scene it should be seperated to another folder.
```suggestion
Scenes should be divided under the **Scenes** folder. If a scene has flow for more than one scene it should be separated to another folder.
```

2021-02-16 12:24 UTC, aslanmehmetsalih approved these changes

2021-02-16 12:34 UTC, merged