Add Validations&Protocols
mobillium/iOS-Guidelines pull request #5
Opened 2021-02-04 13:56 UTC by alihanaktay

2021-02-05 10:33 UTC, emirhanbattalbas approved these changes

2021-02-05 14:31 UTC, kburakka approved these changes

2021-02-08 09:21 UTC, mrtcelebi approved these changes

2021-02-09 12:45 UTC, aslanmehmetsalih requested changes

2021-02-09 12:45 UTC, aslanmehmetsalih commented on project-folder-structure.md
> +> Multiple protocols used in App should store under the **Protocols** folder. These protocols should divided by their usage purpose such as Apple SignIn Protocol, Facebook SignIn Protocol.
typo Apple SignIn Protocol, Facebook SignIn Protocol.
```suggestion
> Multiple protocols used in App should store under the **Protocols** folder. These protocols should divided by their usage purpose such as AppleSignInProtocol, FacebookSignInProtocol.
```

2021-02-09 12:45 UTC, aslanmehmetsalih commented on project-folder-structure.md
> +All validation files should store under the Validation folder. The core files and custom files should store under the Classes folder. If you are using custom rules, these rules should store under the
```suggestion
All validation files should store under the Validation folder. The core files and custom files should store under the Classes folder. If you are using custom rules, these rules should store under the Rules folder divided by their usage. All the constants such as password minimum - maximum length should store under the Constants folder with ValidationConstants.swift naming.
```

2021-02-09 12:58 UTC, aslanmehmetsalih approved these changes

2021-02-09 12:58 UTC, merged